const menuData = [
  // 🍽️ food
  {
    id: 1,
    name: "Nasi Goreng Spesial",
    price: 28000,
    category: "food",
    description: "Special fried rice with egg, chicken, and vegetables",
    quantity: 0,
  },
  {
    id: 2,
    name: "Nasi Goreng Seafood",
    price: 32000,
    category: "food",
    description: "Fried rice with shrimp, squid, and vegetables",
    quantity: 0,
  },
  {
    id: 3,
    name: "Soto Ayam",
    price: 24000,
    category: "food",
    description: "Chicken soup with turmeric broth",
    quantity: 0,
  },
  {
    id: 4,
    name: "Rawon Daging",
    price: 35000,
    category: "food",
    description: "Beef soup with black keluak seasoning",
    quantity: 0,
  },
  {
    id: 5,
    name: "Pecel Lele",
    price: 22000,
    category: "food",
    description: "Fried catfish with sambal and rice",
    quantity: 0,
  },
  {
    id: 6,
    name: "Ayam Geprek Sambal Ijo",
    price: 25000,
    category: "food",
    description: "Crispy chicken smashed with green chili sambal",
    quantity: 0,
  },
  {
    id: 7,
    name: "Ikan Bakar Kecap",
    price: 38000,
    category: "food",
    description: "Grilled fish with sweet soy sauce",
    quantity: 0,
  },
  {
    id: 8,
    name: "Gurame Goreng",
    price: 45000,
    category: "food",
    description: "Deep fried gourami fish",
    quantity: 0,
  },
  {
    id: 9,
    name: "Sate Ayam (10 tusuk)",
    price: 30000,
    category: "food",
    description: "10 skewers of grilled chicken satay with peanut sauce",
    quantity: 0,
  },
  {
    id: 10,
    name: "Sop Buntut",
    price: 55000,
    category: "food",
    description: "Oxtail soup with clear broth",
    quantity: 0,
  },

  // 🥤 drink
  {
    id: 21,
    name: "Es Teh Manis",
    price: 8000,
    category: "drink",
    description: "Sweet iced tea",
    quantity: 0,
  },
  {
    id: 22,
    name: "Es Jeruk",
    price: 10000,
    category: "drink",
    description: "Fresh orange juice with ice",
    quantity: 0,
  },
  {
    id: 23,
    name: "Jus Alpukat",
    price: 18000,
    category: "drink",
    description: "Creamy avocado juice",
    quantity: 0,
  },
  {
    id: 24,
    name: "Jus Mangga",
    price: 16000,
    category: "drink",
    description: "Fresh mango juice",
    quantity: 0,
  },
  {
    id: 25,
    name: "Jus Strawberry",
    price: 18000,
    category: "drink",
    description: "Sweet strawberry juice",
    quantity: 0,
  },
  {
    id: 26,
    name: "Milkshake Coklat",
    price: 20000,
    category: "drink",
    description: "Rich chocolate milkshake",
    quantity: 0,
  },
  {
    id: 27,
    name: "Milkshake Vanilla",
    price: 20000,
    category: "drink",
    description: "Classic vanilla milkshake",
    quantity: 0,
  },
  {
    id: 28,
    name: "Es Kopi Susu",
    price: 18000,
    category: "drink",
    description: "Iced coffee with milk",
    quantity: 0,
  },
  {
    id: 29,
    name: "Cappuccino",
    price: 22000,
    category: "drink",
    description: "Espresso with steamed milk and foam",
    quantity: 0,
  },
  {
    id: 30,
    name: "Matcha Latte",
    price: 22000,
    category: "drink",
    description: "Green tea latte with milk",
    quantity: 0,
  },

  // 🍪 snack
  {
    id: 41,
    name: "Gado-Gado",
    price: 22000,
    category: "snack",
    description: "Vegetables salad with peanut sauce",
    quantity: 0,
  },
  {
    id: 42,
    name: "Ketoprak",
    price: 20000,
    category: "snack",
    description: "Rice cake, tofu, and vegetables with peanut sauce",
    quantity: 0,
  },
  {
    id: 43,
    name: "Tahu Tek Surabaya",
    price: 21000,
    category: "snack",
    description: "Fried tofu with rice cake and peanut sauce",
    quantity: 0,
  },
  {
    id: 44,
    name: "Es Cendol",
    price: 15000,
    category: "snack",
    description: "Traditional iced cendol with coconut milk",
    quantity: 0,
  },
  {
    id: 45,
    name: "Es Dawet Ayu",
    price: 14000,
    category: "snack",
    description: "Iced dawet with palm sugar and coconut milk",
    quantity: 0,
  },
  {
    id: 46,
    name: "Es Campur",
    price: 18000,
    category: "snack",
    description: "Mixed ice dessert with fruits and jelly",
    quantity: 0,
  },
  {
    id: 47,
    name: "Es Teler",
    price: 20000,
    category: "snack",
    description: "Mixed tropical fruit dessert with coconut milk",
    quantity: 0,
  },
  {
    id: 48,
    name: "Keripik Singkong",
    price: 12000,
    category: "snack",
    description: "Crispy cassava chips",
    quantity: 0,
  },
  {
    id: 49,
    name: "Pisang Goreng",
    price: 15000,
    category: "snack",
    description: "Fried banana with crispy coating",
    quantity: 0,
  },
  {
    id: 50,
    name: "Tempe Mendoan",
    price: 12000,
    category: "snack",
    description: "Half-fried soft tempeh with flour batter",
    quantity: 0,
  },
];

export default menuData;
